/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author arnavprabhale
 */
public class Conversion extends javax.swing.JFrame
{

    /**
     * Creates new form Conversion
     */
    
    
    FirstPage fp;
    Conversion me;
    SimpleInterset simpleInterset;
    Fibonacchi fseries;
    
    
    public Conversion()
    {
        initComponents();
        btndecimalToBinary.setBackground(new Color(123, 133, 138));
    }
    
    public Conversion(FirstPage ref)
    {
        fp = ref;
        me = this;
        initComponents();
        btndecimalToBinary.setBackground(new Color(123, 133, 138));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        subPanel1 = new javax.swing.JPanel();
        subPanel5 = new javax.swing.JPanel();
        btndecimalToBinary = new javax.swing.JButton();
        btndecimalToOctal = new javax.swing.JButton();
        btndecimalToHexadecimal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbloutputname = new javax.swing.JLabel();
        txtoutput = new javax.swing.JTextField();
        txtinput = new javax.swing.JTextField();
        btnconvert = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(96, 106, 116));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subPanel1.setBackground(new java.awt.Color(134, 143, 152));
        subPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONVERSIONS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ayuthaya", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        subPanel5.setBackground(new java.awt.Color(168, 173, 180));
        subPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btndecimalToBinary.setBackground(new java.awt.Color(195, 200, 205));
        btndecimalToBinary.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        btndecimalToBinary.setForeground(new java.awt.Color(51, 51, 51));
        btndecimalToBinary.setText("DECIMAL TO BINARY");
        btndecimalToBinary.setSize(new java.awt.Dimension(100, 35));
        btndecimalToBinary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndecimalToBinaryActionPerformed(evt);
            }
        });

        btndecimalToOctal.setBackground(new java.awt.Color(195, 200, 205));
        btndecimalToOctal.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        btndecimalToOctal.setForeground(new java.awt.Color(51, 51, 51));
        btndecimalToOctal.setText("DECIMAL TO OCTAL");
        btndecimalToOctal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndecimalToOctalActionPerformed(evt);
            }
        });

        btndecimalToHexadecimal.setBackground(new java.awt.Color(195, 200, 205));
        btndecimalToHexadecimal.setFont(new java.awt.Font("Ayuthaya", 1, 18)); // NOI18N
        btndecimalToHexadecimal.setForeground(new java.awt.Color(51, 51, 51));
        btndecimalToHexadecimal.setText("DECIMAL TO HEXADECIMAL");
        btndecimalToHexadecimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btndecimalToHexadecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanel5Layout = new javax.swing.GroupLayout(subPanel5);
        subPanel5.setLayout(subPanel5Layout);
        subPanel5Layout.setHorizontalGroup(
            subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndecimalToOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btndecimalToHexadecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(btndecimalToBinary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        subPanel5Layout.setVerticalGroup(
            subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndecimalToBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btndecimalToOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btndecimalToHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(168, 173, 180));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Avenir", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DECIMAL");

        lbloutputname.setFont(new java.awt.Font("Avenir", 1, 18)); // NOI18N
        lbloutputname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbloutputname.setText("BINARY");

        txtoutput.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        txtoutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtoutput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtoutputActionPerformed(evt);
            }
        });
        txtoutput.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtoutputKeyTyped(evt);
            }
        });

        txtinput.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        txtinput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtinput.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtinputActionPerformed(evt);
            }
        });
        txtinput.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtinputKeyTyped(evt);
            }
        });

        btnconvert.setFont(new java.awt.Font("Avenir", 1, 18)); // NOI18N
        btnconvert.setText("CONVERT");
        btnconvert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnconvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtinput))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbloutputname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtoutput, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbloutputname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        jButton1.setBackground(new java.awt.Color(178, 188, 192));
        jButton1.setFont(new java.awt.Font("Kailasa", 0, 18)); // NOI18N
        jButton1.setText("SIMPLE INTEREST CALCULATOR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(178, 188, 192));
        jButton2.setFont(new java.awt.Font("Kailasa", 0, 18)); // NOI18N
        jButton2.setText("FIBONACCI SERIES");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(178, 188, 192));
        jButton3.setFont(new java.awt.Font("Kailasa", 0, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanel1Layout = new javax.swing.GroupLayout(subPanel1);
        subPanel1.setLayout(subPanel1Layout);
        subPanel1Layout.setHorizontalGroup(
            subPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(subPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(subPanel1Layout.createSequentialGroup()
                        .addComponent(subPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        subPanel1Layout.setVerticalGroup(
            subPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanel1Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(subPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(subPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(subPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndecimalToBinaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndecimalToBinaryActionPerformed
    {//GEN-HEADEREND:event_btndecimalToBinaryActionPerformed
        // TODO add your handling code here:
        btndecimalToBinary.setBackground(new Color(123, 133, 138));
        btndecimalToOctal.setBackground(new Color(195, 200, 205));
        btndecimalToHexadecimal.setBackground(new Color(195, 200, 205));
        lbloutputname.setText("BINARY");
        txtinput.setText("");
        txtoutput.setText("");
       
    }//GEN-LAST:event_btndecimalToBinaryActionPerformed

    private void btndecimalToHexadecimalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndecimalToHexadecimalActionPerformed
    {//GEN-HEADEREND:event_btndecimalToHexadecimalActionPerformed
        // TODO add your handling code here:
        btndecimalToHexadecimal.setBackground(new Color(123, 133, 138));
        btndecimalToBinary.setBackground(new Color(195, 200, 205));
        btndecimalToOctal.setBackground(new Color(195, 200, 205));
        lbloutputname.setText("HEXADECIMAL");
        txtinput.setText("");
        txtoutput.setText("");
    }//GEN-LAST:event_btndecimalToHexadecimalActionPerformed

    private void btndecimalToOctalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btndecimalToOctalActionPerformed
    {//GEN-HEADEREND:event_btndecimalToOctalActionPerformed
        // TODO add your handling code here:
        btndecimalToOctal.setBackground(new Color(123, 133, 138));
        btndecimalToBinary.setBackground(new Color(195, 200, 205));
        btndecimalToHexadecimal.setBackground(new Color(195, 200, 205));
        lbloutputname.setText("OCTAL");
        txtinput.setText("");
        txtoutput.setText("");
        
    }//GEN-LAST:event_btndecimalToOctalActionPerformed

    private void txtoutputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtoutputActionPerformed
    {//GEN-HEADEREND:event_txtoutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoutputActionPerformed

    private void txtinputKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtinputKeyTyped
    {//GEN-HEADEREND:event_txtinputKeyTyped
        CommonFunctions.conversionValidation(evt);
    }//GEN-LAST:event_txtinputKeyTyped

    private void txtoutputKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtoutputKeyTyped
    {//GEN-HEADEREND:event_txtoutputKeyTyped
        CommonFunctions.noInputValidation(evt);
    }//GEN-LAST:event_txtoutputKeyTyped

    private void txtinputActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtinputActionPerformed
    {//GEN-HEADEREND:event_txtinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinputActionPerformed

    private void btnconvertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnconvertActionPerformed
    {//GEN-HEADEREND:event_btnconvertActionPerformed
        // TODO add your handling code here:
        try
        {
            if("BINARY".equals(lbloutputname.getText()))
            {
                int x = Integer.parseInt(txtinput.getText());
                String s = Integer.toBinaryString(x);
                txtoutput.setText(s);
            }
            else if("OCTAL".equals(lbloutputname.getText()))
            {
                int x = Integer.parseInt(txtinput.getText());
                String s = Integer.toOctalString(x);
                txtoutput.setText(s);
            }
            else if("HEXADECIMAL".equals(lbloutputname.getText()))
            {
                int x = Integer.parseInt(txtinput.getText());
                String s = Integer.toHexString(x);
                txtoutput.setText(s);
            }
            else
            {
                
            }    
        } 
        catch (NumberFormatException a)
        {
            JOptionPane.showMessageDialog(btnconvert, "Please enter Valid Input", "ERROR", JOptionPane.ERROR_MESSAGE);         
            txtinput.setText("");
            txtoutput.setText("");
        }
    }//GEN-LAST:event_btnconvertActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fp = new FirstPage();
        fp.setVisible(true);
        me.setVisible(false);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        simpleInterset = new SimpleInterset(fp);
        simpleInterset.setVisible(true);
        me.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fseries = new Fibonacchi(fp);
        fseries.setVisible(true);
        me.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Conversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconvert;
    private javax.swing.JButton btndecimalToBinary;
    private javax.swing.JButton btndecimalToHexadecimal;
    private javax.swing.JButton btndecimalToOctal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbloutputname;
    private javax.swing.JPanel subPanel1;
    private javax.swing.JPanel subPanel5;
    private javax.swing.JTextField txtinput;
    private javax.swing.JTextField txtoutput;
    // End of variables declaration//GEN-END:variables
}
