/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author arnavprabhale
 */
public class FirstPage extends javax.swing.JFrame
{

    /**
     * Creates new form FirstPage
     */
    
    JButton  lblinterest, lblfseries;
    JButton lblconversion, lblexit, btnquote, btnquote2;
    FirstPage fp;
    Conversion conversionpage;
    SimpleInterset simpleInterset;
    Fibonacchi fseries;
    
   
    
    
    public FirstPage()
    {
        initComponents();
        CommonFunctions.addlabelBackground(lblmainlabel, "/Users/arnavprabhale/NetBeansProjects/RealApplications/src/main/java/images2/fixfirst.jpeg");
        addComponents();
        fp = this;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblmainlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmainlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblmainlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmainlabel;
    // End of variables declaration//GEN-END:variables

    private void addComponents()
    {
        Font f = new Font("AppleMyungjo", Font.BOLD, 30);
        Font f1 = new Font("Academy Engraved LET", Font.PLAIN, 40);
        
        //String s = "<html>Conversions<br/>1. Decimal To Binary<br/>2. Decimal To Octal<br/>3. Decimal to Hexadecimal</html>\"";
        lblconversion = new JButton("Conversions");
        lblconversion.setFont(f);
        lblconversion.setForeground(Color.WHITE);
        lblconversion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblconversion.setBounds(65, 500, 250, 100);
        lblconversion.setOpaque(false);
        lblconversion.setContentAreaFilled(false);
        lblconversion.setBorderPainted(true);
        lblconversion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblmainlabel.add(lblconversion);
        lblconversion.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                conversionpage = new Conversion(fp);
                conversionpage.setVisible(true);
                fp.setVisible(false);
            }
        });
        
        String s = "<html>Simple Interest<br/>Calculator</html>";
        lblinterest = new JButton(s);
        lblinterest.setFont(f);
        lblinterest.setForeground(Color.WHITE);
        lblinterest.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblinterest.setOpaque(false);
        lblinterest.setContentAreaFilled(false);
        lblinterest.setBorderPainted(true);
        lblinterest.setBounds(375, 500, 250, 100);
        lblinterest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblmainlabel.add(lblinterest);
        lblinterest.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                simpleInterset = new SimpleInterset(fp);
                simpleInterset.setVisible(true);
                fp.setVisible(false);
            }
        });
        
        String s1 = "<html>Fibonacci<br/>Series</html>";
        lblfseries = new JButton(s1);
        lblfseries.setFont(f);
        lblfseries.setForeground(Color.WHITE);
        lblfseries.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblfseries.setOpaque(false);
        lblfseries.setContentAreaFilled(false);
        lblfseries.setBorderPainted(true);
        lblfseries.setBounds(685, 500, 250, 100);
        lblfseries.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblmainlabel.add(lblfseries);
        lblfseries.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                fseries = new Fibonacchi(fp);
                fseries.setVisible(true);
                fp.setVisible(false);
            }
        });
        
        lblexit = new JButton("Exit");
        lblexit.setFont(f);
        lblexit.setForeground(Color.WHITE);
        lblexit.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblexit.setBounds(905, 630, 75, 50);
        lblexit.setOpaque(false);
        lblexit.setContentAreaFilled(false);
        lblexit.setBorderPainted(true);
        lblexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblmainlabel.add(lblexit);
        lblexit.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                int result = JOptionPane.showConfirmDialog(lblmainlabel, "Want To Exit ?", "Are You Sure", JOptionPane.YES_NO_OPTION);

                if(JOptionPane.YES_OPTION == result)
                {
                    fp.dispose();
                    System.exit(0);
                }
                else
                {

                }
            }
        });
        
        String str = "I will make all the Calculations";
        String str2 = "You have to do the rest";
        
        btnquote = new JButton(str);
        btnquote.setFont(f1);
        btnquote.setForeground(Color.WHITE);
        btnquote.setOpaque(false);
        btnquote.setContentAreaFilled(false);
        btnquote.setBorderPainted(false);
        btnquote.setBounds(5, 200, 545, 50);
        lblmainlabel.add(btnquote);
        
        
        btnquote2 = new JButton(str2);
        btnquote2.setFont(f1);
        btnquote2.setForeground(Color.WHITE);
        btnquote2.setOpaque(false);
        btnquote2.setContentAreaFilled(false);
        btnquote2.setBorderPainted(false);
        btnquote2.setBounds(5, 250, 430, 50);
        lblmainlabel.add(btnquote2);
    }
}
